name: cached_query

packages:
  - packages/**

ignore:
  # e.g. ignore example apps
  - "packages/**/example"
ide:
  intellij: false

scripts:
  get:
    exec: dart pub get
  analyze:
    exec: dart analyze .
  test:
    run: |
      melos exec -c 6 --fail-fast -- \
        "flutter test --no-pub"
    description: Run `flutter test` for a specific package.
    select-package:
      dir-exists:
        - test
      ignore:
        - 'examples/**'
