name: cached_storage
description: A storage addon for cached_query. Built on top of the Sqflite package.
version: 1.0.0
repository: https://github.com/D-James-GH/cached_query/tree/main/packages/cached_query_flutter
documentation: https://cachedquery.dev/
homepage: https://cachedquery.dev/
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
    # cached_query: ^1.0.0
  cached_query:
    git:
      url: https://github.com/CyberMindWorks/cached_query.git
      path: packages/cached_query
      ref: d6dbddc4e215329a2daae184b7a5cf7375cc51bb
  sqflite: ^2.2.8+4
  path: ^1.8.2

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.24.1
  sqflite_common: ^2.4.5+1
  mockito: ^5.4.0
  build_runner:
