name: cached_storage
description: A storage addon for cached_query. Built on top of the Sqflite package.
version: 1.0.0-dev.1
repository: https://github.com/D-James-GH/cached_query/tree/main/packages/cached_query_flutter
documentation: https://cachedquery.dev/
homepage: https://cachedquery.dev/

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cached_query: 0.6.0
  sqflite: ^2.2.8+4
  path: ^1.8.2


dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.24.3
  sqflite_common: ^2.4.5+1
  mockito: ^5.4.1
  build_runner:
