name: cached_storage
description: A storage addon for cached_query. Built on top of the Sqflite package.
version: 2.0.4
repository: https://github.com/D-James-GH/cached_query/tree/main/packages/cached_query_flutter
documentation: https://cachedquery.dev/
homepage: https://cachedquery.dev/
publish_to: none

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cached_query:
    git:
      url: https://github.com/CyberMindWorks/cached_query.git
      path: packages/cached_query
      ref: f69fd4da492c69f29a5baeb441551d740a659b16
  sqflite: ^2.3.3+1
  path: ^1.8.3

dev_dependencies:
  flutter_lints: ^3.0.0
  test: ^1.24.8
  sqflite_common: ^2.5.0
  mockito: ^5.4.2
  build_runner:
