name: cached_storage
description: A storage addon for cached_query
version: 0.0.1-dev.1
homepage:
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cached_query:
    path: ../cached_query
  sqflite: ^2.0.2+1
  path: ^1.8.1


dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.20.1
  mockito: ^5.2.0
  build_runner:
