name: cached_storage
description: A storage addon for cached_query
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cached_query:
    path: ../cached_query
  sqflite: ^2.0.1
  path: ^1.8.0


dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.20.1