name: cached_query_flutter
description: Flutter widgets for use with Cached Query
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cached_query:
    path: ../cached_query

dev_dependencies:
  flutter_test:
    sdk: flutter
