name: cached_query_flutter
description: Assortment of builders and addons for use with Cached Query in flutter.
version: 0.0.1-dev.1
repository: https://github.com/D-James-GH/cached_query/tree/main/packages/cached_query_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cached_query: ^0.0.1
  connectivity_plus: ^2.3.5

dev_dependencies:
  flutter_lints: ^2.0.1
  mockito: ^5.2.0
  connectivity_plus_platform_interface: ^1.2.1
  build_runner:
  flutter_test:
    sdk: flutter
