name: cached_query
description: A simple library for dealing with server state in dart and flutter.
version: 0.0.3
repository: https://github.com/D-James-GH/cached_query

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  rxdart: ^0.27.4
  meta: ^1.7.0

dev_dependencies:
  test: ^1.21.1
  flutter_lints: ^2.0.1
  build_runner:
  mockito: ^5.2.0

